---
- name: "Apache installation using docker"
  hosts: prod
  pre_tasks:
    - name: download pip script
      get_url:
         url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
         dest: /tmp/get-pip.py
    - name: install python-pip
      command: python2.7 /tmp/get-pip.py
    - name: install docekr python
      pip: name=docker-py
  tasks:
  - name: Create Apache conteneur
    docker_container:
        name: webapp
        image: httpd
        ports:
            - "80:80"
