all:
  vars: 
    ansible_user: admin
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

prod: 
  hosts: 
    client:
      ansible_host: 10.0.0.4
  vars:
    ansible_password: admin
    env: production 
